services:
  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  web:
    build: .
    env_file:
      - .env
    environment:
      - PORT=${PORT:-9000}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./web/templates:/app/web/templates:ro
    restart: unless-stopped

volumes:
  db-data:
